name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup Yarn Berry
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate
          yarn --version

      - name: Install deps
        run: yarn install --immutable

      - uses: calcit-lang/setup-calcit@3b5843cb725963bb4ee158cfe49dad877134963e # v1

      - name: "test"
        run: caps --ci && mode=dev calcit calcit.cirru --entry test

      - name: "test js"
        run: >
          mode=dev calcit calcit.cirru --entry test js
          && mode=dev node test.mjs
